<?php
/**
 * Created by PhpStorm.
 * User: pengjixiang
 * Date: 17/5/19
 * Time: 下午2:10
 */

namespace app\controllers;
use app\api\UserApi;
use yii;
use app\api\SmsSendApi;
class PersonalCenterController extends WxController
{
    public function beforeAction($action)
    {

        $this->checkOpenid();
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
    /**
     * 登录页面
     * @return string
     */
    public function actionLoginPage(){
        return $this->renderPartial("login");
    }

    /**
     * 个人中心
     * @return string|yii\web\Response
     */
    public function actionSetting(){
        if(!$this->checkCustomerLogin()){
            yii::$app->session->set("last_url","/personal-center/setting");
           return $this->redirect(["/personal-center/login-page"]);
        }
        $info=yii::$app->session->get("user");
        return $this->renderPartial("setting",["info"=>$info]);
    }

    /**
     * 实时监控
     * @return string
     */
    public function actionDrinkMonitor(){
        if(!$this->checkCustomerLogin()){
            yii::$app->session->set("last_url","/personal-center/drink-monitor");
            return $this->redirect(["/personal-center/login-page"]);
        }
        $todayInfo=(new UserApi())->todayInfo();
        if($todayInfo->state!=0){
            $this->toError();
        }
        $user= yii::$app->session->get("user");
        return $this->renderPartial("drink-monitor",["today_info"=>$todayInfo->result,"user"=>$user]);
    }

    /**
     * 实时饮水报表
     * @return string
     */
    public function actionDrinkChart(){
        if(!$this->checkCustomerLogin()){
            yii::$app->session->set("last_url","/personal-center/drink-chart");
            return $this->redirect(["/personal-center/login-page"]);
        }
        $logs=(new UserApi())->getLogs();
        if($logs->state!=0){
            $this->toError();
        }
        $datax=[];
        $datay=[];
        foreach($logs->result as $val){
                array_push($datax,substr($val->dt,11,5));
                array_push($datay,$val->ml);
        }
        return $this->renderPartial("drink-chart",["datax"=>$datax,"datay"=>$datay]);
    }
    /**
     * 登录
     */
    public function actionLogin(){
        $mobile=yii::$app->request->get("mobile");
        $vcode=yii::$app->request->get("vcode");
        $res=(new UserApi())->post($mobile,$vcode);
        if($res->state==0){
            $this->saveCustomerInfo($res->result);
        }
        return $this->jsonReturn($res);
    }

    /**
     * 获取短信
     */
    public function actionGetSms(){
        $tel=yii::$app->request->get("mobile");
        $this->jsonReturn((new SmsSendApi())->post($tel));
    }

    /**
     * 保存饮水计划
     */
    public function actionSavewaterplan(){
        $ml=yii::$app->request->get("ml");
        $res=(new UserApi())->saveWaterPlan($ml);
        if($res->state==0){
            //更新饮水计划
            $user= yii::$app->session->get("user");
            $user->waterplan=$ml;
            $this->saveUser($user);
        }
        return $this->jsonReturn($res);
    }
    public function actionSkip(){
        $last_url= yii::$app->session->get("last_url");
        $last_url_param= yii::$app->session->get("last_url_params");
        $url="/index.php/".$last_url."?";
        if(!empty($last_url_param)){
           foreach($last_url_param as $key=>$val){
               $url.="&$key=$val";
           }
        }
        header("Location:".$url);
        exit();
    }


}